language: cpp
before_install:
   - sudo apt-get -qq update
   - test -n $CC && unset CC   #Fix for MPI trouble
install:
   - sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
compiler:
   - clang
   - gcc
script:
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=NO MFEM_CXX=$CXX && make
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=YES MFEM_CXX=$CXX && make
   - mpic++ --version
   - mpicxx --version
   - mpiCC --version
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=YES MFEM_CXX=mpic++ && make
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=YES MFEM_CXX=mpicxx && make
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=YES MFEM_CXX=mpiCC && make
