language: cpp
before_install:
   - sudo apt-get -qq update
   - test -n $CC && unset CC   #Fix for MPI trouble
install:
   - sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
compiler:
   - clang
   - gcc
env:
   - DEBUG=YES
   - DEBUG=NO
   - MPI=YES 
   - MPI=NO
script:
   - if [[ $MPI == 'YES' ]]; then $CXX "mpic++" ; fi
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=$DEBUG MFEM_CXX=$CXX && make