language: cpp
install:
#    OpenMPI install
   - if test $TRAVIS_OS_NAME == "linux"; then sudo apt-get install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev; else sudo brew install open-mpi; fi || true
#    Hypre install   
   - wget https://computation.llnl.gov/project/linear_solvers/download/hypre-2.10.0b.tar.gz --no-check-certificate
   - tar xvzf hypre-2.10.0b.tar.gz
   - cd hypre-2.10.0b/src
   - ./configure --disable-fortran
   - cd ../..
#    Metis install   
   - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
   - tar xvzf metis-4.0.3.tar.gz
   - cd metis-4.0.3
   - make
   - cd ..
   - ln -s metis-4.0.3 metis-4.0
compiler:
   - clang
   - gcc
os:
   - linux
   - osx
env:
   - DEBUG=YES MPI=YES 
   - DEBUG=NO MPI=YES
   - DEBUG=YES MPI=NO 
   - DEBUG=NO MPI=NO
script:
   - if test $MPI == "YES"; then export MYCXX=mpic++; else export MYCXX=$CXX; fi || true
   - make config MFEM_USE_MPI=$MPI MFEM_DEBUG=$DEBUG MFEM_CXX=$MYCXX && make
matrix:
   exclude:
      - compiler: clang
        env: DEBUG=NO MPI=YES
      - compiler: clang
        env: DEBUG=YES MPI=YES
