language: cpp
before_install:
   - sudo apt-get -qq update
   - test -n $CC && unset CC   #Fix for MPI trouble
install:
   - sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
compiler:
   - clang
   - gcc
os:
   - linux
   - osx
env:
   - DEBUG=YES MPI=YES 
   - DEBUG=NO MPI=YES
   - DEBUG=YES MPI=NO 
   - DEBUG=NO MPI=NO
before_script:
   - 
script:
   - test $MPI == "YES" && setenv CXX mpic++
   - make config MFEM_USE_MPI=NO MFEM_DEBUG=$DEBUG MFEM_CXX=$CXX && make
matrix:
   exclude:
      - compiler: clang
        env: MPI=YES